//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamenFinalWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visitas
    {
        public int Id { get; set; }
        public string Motivo_visita { get; set; }
        public Nullable<System.DateTime> Fecha_visita { get; set; }
        public Nullable<System.TimeSpan> HoraEntrada { get; set; }
        public Nullable<System.TimeSpan> HoraSalida { get; set; }
        public string NombreCompleto { get; set; }
        public Nullable<int> IdContacto { get; set; }
    
        public virtual Contactos Contactos { get; set; }
    }
}
